import type { RoomTint } from './shell'
import type { ItemId } from './items'

// Data-driven rooms. A spec is pure data (unit-tested for map integrity);
// buildRoomFromSpec turns it into a Room. Cells are 0..7 on the 8x8 grid.
// Doorways sit mid-edge: north (4,0), south (4,7), west (0,4), east (7,4).

export type Direction = 'north' | 'south' | 'east' | 'west'

export interface Cell {
  x: number
  z: number
}

export interface RoomSpec {
  id: string
  tint: RoomTint
  exits: { direction: Direction; target: string }[]
  spawn: Cell
  platforms?: (Cell & { height: number })[]
  pushBlocks?: Cell[]
  spikes?: Cell[]
  guards?: { from: Cell; to: Cell; speed?: number }[]
  ghosts?: Cell[]
  pickups?: (Cell & { item: ItemId; y?: number })[]
  movingPlatforms?: { from: Cell; to: Cell; height: number }[]
  pathGuards?: { path: Cell[] }[]
  tables?: (Cell & { height: number })[]
  vanishing?: (Cell & { height: number })[]
  balls?: { from: Cell; to: Cell }[]
  cauldron?: Cell & { height: number }
  wizard?: Cell
  flames?: (Cell & { height: number })[]
  // Read off map.png (tools/map): doors, blocks, spike beds, some furniture.
  mapped?: boolean
}

const OPPOSITE: Record<Direction, Direction> = { north: 'south', south: 'north', east: 'west', west: 'east' }

export function oppositeOf(direction: Direction): Direction {
  return OPPOSITE[direction]
}

// Walking out through a door lands you just inside the opposite edge.
export function entryFor(direction: Direction): { x: number; z: number } {
  switch (direction) {
    case 'south': return { x: 9, z: 1 }
    case 'north': return { x: 9, z: 15 }
    case 'east': return { x: 1, z: 9 }
    case 'west': return { x: 15, z: 9 }
  }
}

// Exits of the five hand-built rooms, kept here so the map test can check
// that every doorway on the whole map leads somewhere and back.
// The five hand-built rooms are gone; every room is a spec now.
export const LEGACY_ROOM_LINKS: { id: string; exits: { direction: Direction; target: string }[] }[] = []

// Generated by tools/map/emit.py from the map reading in tools/map/rooms.json;
// see docs/MAP.md. Edit the reading and regenerate rather than editing here.
export const ROOM_SPECS: RoomSpec[] = [
  {
    id: 'room-001', tint: 'yellow',
    exits: [{ direction: 'west', target: 'map--1-0' }, { direction: 'east', target: 'map-1-0' }, { direction: 'south', target: 'map-0-1' }, { direction: 'north', target: 'map-0--1' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 1, z: 2, height: 1 }, { x: 2, z: 1, height: 1 }, { x: 1, z: 5, height: 1 }, { x: 5, z: 1, height: 1 }, { x: 5, z: 6, height: 1 }, { x: 6, z: 5, height: 1 }],
    cauldron: { x: 4, z: 4, height: 0 },
    wizard: { x: 4, z: 2 },
  },
  {
    id: 'map--1-0', tint: 'blue', mapped: true,
    exits: [{ direction: 'east', target: 'room-001' }, { direction: 'south', target: 'map--1-1' }, { direction: 'north', target: 'map--1--1' }, { direction: 'west', target: 'map--2-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 2, height: 2 }, { x: 4, z: 2, height: 2 }, { x: 2, z: 3, height: 2 }, { x: 2, z: 4, height: 2 }, { x: 5, z: 3, height: 2 }, { x: 5, z: 4, height: 2 }, { x: 3, z: 5, height: 2 }, { x: 4, z: 5, height: 2 }],
    spikes: [{ x: 2, z: 2 }, { x: 2, z: 5 }, { x: 5, z: 2 }, { x: 5, z: 5 }],
  },
  {
    id: 'map-0--1', tint: 'purple', mapped: true,
    exits: [{ direction: 'south', target: 'room-001' }, { direction: 'north', target: 'map-0--2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 3, height: 3 }, { x: 3, z: 4, height: 3 }, { x: 4, z: 3, height: 3 }, { x: 4, z: 4, height: 3 }, { x: 4, z: 5, height: 2 }, { x: 4, z: 6, height: 1 }],
    spikes: [{ x: 2, z: 4 }, { x: 5, z: 3 }, { x: 5, z: 4 }],
  },
  {
    id: 'map-0-1', tint: 'green', mapped: true,
    exits: [{ direction: 'west', target: 'map--1-1' }, { direction: 'east', target: 'map-1-1' }, { direction: 'north', target: 'room-001' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    spikes: [{ x: 0, z: 2 }, { x: 1, z: 0 }, { x: 3, z: 3 }, { x: 3, z: 5 }, { x: 4, z: 2 }, { x: 5, z: 4 }, { x: 5, z: 6 }, { x: 6, z: 6 }],
    pathGuards: [{ path: [{ x: 7, z: 6 }, { x: 7, z: 7 }, { x: 2, z: 7 }, { x: 7, z: 7 }] }],
  },
  {
    id: 'map-1-0', tint: 'blue', mapped: true,
    exits: [{ direction: 'west', target: 'room-001' }, { direction: 'east', target: 'map-2-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 4, z: 2, height: 3 }, { x: 4, z: 3, height: 1 }, { x: 4, z: 4, height: 1 }, { x: 4, z: 5, height: 3 }],
    flames: [{ x: 4, z: 3, height: 1 }],
  },
  {
    id: 'map--1--1', tint: 'green', mapped: true,
    exits: [{ direction: 'south', target: 'map--1-0' }, { direction: 'north', target: 'map--1--2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 2, z: 4, height: 1 }, { x: 3, z: 4, height: 1 }, { x: 4, z: 4, height: 1 }, { x: 5, z: 4, height: 1 }],
  },
  {
    id: 'map--1-1', tint: 'purple', mapped: true,
    exits: [{ direction: 'east', target: 'map-0-1' }, { direction: 'south', target: 'map--1-2' }, { direction: 'north', target: 'map--1-0' }, { direction: 'west', target: 'map--2-1' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map--2-0', tint: 'purple', mapped: true,
    exits: [{ direction: 'west', target: 'map--3-0' }, { direction: 'east', target: 'map--1-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 2, z: 3, height: 1 }],
    balls: [{ from: { x: 3, z: 2 }, to: { x: 3, z: 6 } }],
  },
  {
    id: 'map-0--2', tint: 'yellow', mapped: true,
    exits: [{ direction: 'south', target: 'map-0--1' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 2, z: 1, height: 4 }, { x: 2, z: 2, height: 2 }, { x: 6, z: 1, height: 4 }, { x: 6, z: 5, height: 4 }],
    spikes: [{ x: 5, z: 1 }, { x: 6, z: 4 }],
  },
  {
    id: 'map-1-1', tint: 'purple', mapped: true,
    exits: [{ direction: 'west', target: 'map-0-1' }, { direction: 'east', target: 'map-2-1' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 3, height: 1 }, { x: 2, z: 4, height: 1 }, { x: 5, z: 3, height: 1 }, { x: 5, z: 4, height: 1 }],
    spikes: [{ x: 3, z: 2 }, { x: 3, z: 3 }, { x: 3, z: 4 }, { x: 3, z: 5 }, { x: 4, z: 2 }, { x: 4, z: 3 }, { x: 4, z: 4 }, { x: 4, z: 5 }],
    balls: [{ from: { x: 1, z: 1 }, to: { x: 6, z: 1 } }],
  },
  {
    id: 'map-2-0', tint: 'purple', mapped: true,
    exits: [{ direction: 'west', target: 'map-1-0' }, { direction: 'east', target: 'map-3-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map--1--2', tint: 'purple', mapped: true,
    exits: [{ direction: 'south', target: 'map--1--1' }, { direction: 'north', target: 'map--1--3' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map--1-2', tint: 'green', mapped: true,
    exits: [{ direction: 'south', target: 'map--1-3' }, { direction: 'north', target: 'map--1-1' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    spikes: [{ x: 2, z: 2 }, { x: 5, z: 2 }, { x: 2, z: 4 }, { x: 5, z: 4 }],
    pathGuards: [{ path: [{ x: 3, z: 3 }, { x: 4, z: 3 }, { x: 4, z: 4 }, { x: 3, z: 4 }] }],
  },
  {
    id: 'map--2-1', tint: 'yellow', mapped: true,
    exits: [{ direction: 'west', target: 'map--3-1' }, { direction: 'east', target: 'map--1-1' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map--3-0', tint: 'green', mapped: true,
    exits: [{ direction: 'west', target: 'map--4-0' }, { direction: 'east', target: 'map--2-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    spikes: [{ x: 3, z: 3 }, { x: 3, z: 4 }, { x: 4, z: 3 }, { x: 4, z: 4 }, { x: 5, z: 3 }, { x: 5, z: 4 }],
  },
  {
    id: 'map-2-1', tint: 'blue', mapped: true,
    exits: [{ direction: 'west', target: 'map-1-1' }, { direction: 'south', target: 'map-2-2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 0, z: 2, height: 1 }, { x: 0, z: 1, height: 2 }, { x: 0, z: 0, height: 3 }, { x: 1, z: 0, height: 3 }, { x: 3, z: 0, height: 4 }, { x: 5, z: 0, height: 4 }],
    spikes: [{ x: 7, z: 1 }, { x: 7, z: 2 }, { x: 7, z: 3 }],
  },
  {
    id: 'map-3-0', tint: 'blue', mapped: true,
    exits: [{ direction: 'north', target: 'map-3--1' }, { direction: 'west', target: 'map-2-0' }, { direction: 'east', target: 'map-4-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map--1--3', tint: 'green', mapped: true,
    exits: [{ direction: 'south', target: 'map--1--2' }, { direction: 'north', target: 'map--1--4' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 1, height: 1 }, { x: 4, z: 1, height: 1 }, { x: 4, z: 6, height: 1 }],
    ghosts: [{ x: 5, z: 2 }, { x: 5, z: 5 }],
  },
  {
    id: 'map--1-3', tint: 'blue', mapped: true,
    exits: [{ direction: 'south', target: 'map--1-4' }, { direction: 'north', target: 'map--1-2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 2, z: 5, height: 3 }, { x: 3, z: 4, height: 3 }, { x: 4, z: 3, height: 3 }, { x: 5, z: 2, height: 3 }],
    pickups: [{ x: 3, z: 3, item: 'goblet' }],
  },
  {
    id: 'map--3-1', tint: 'purple', mapped: true,
    exits: [{ direction: 'east', target: 'map--2-1' }, { direction: 'west', target: 'map--4-1' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 3, height: 1 }, { x: 4, z: 4, height: 1 }],
    spikes: [{ x: 3, z: 4 }, { x: 4, z: 3 }],
    pickups: [{ x: 2, z: 3, item: 'gem' }],
  },
  {
    id: 'map--4-0', tint: 'blue', mapped: true,
    exits: [{ direction: 'west', target: 'map--5-0' }, { direction: 'east', target: 'map--3-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 2, height: 2 }, { x: 2, z: 5, height: 2 }, { x: 5, z: 2, height: 2 }, { x: 5, z: 5, height: 2 }],
    balls: [{ from: { x: 1, z: 1 }, to: { x: 6, z: 1 } }, { from: { x: 4, z: 2 }, to: { x: 4, z: 6 } }],
  },
  {
    id: 'map-2-2', tint: 'yellow', mapped: true,
    exits: [{ direction: 'east', target: 'map-3-2' }, { direction: 'north', target: 'map-2-1' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map-3--1', tint: 'purple', mapped: true,
    exits: [{ direction: 'south', target: 'map-3-0' }, { direction: 'east', target: 'map-4--1' }, { direction: 'north', target: 'map-3--2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 0, z: 3, height: 4 }, { x: 0, z: 4, height: 4 }, { x: 0, z: 5, height: 3 }, { x: 0, z: 6, height: 2 }, { x: 0, z: 7, height: 1 }],
    spikes: [{ x: 0, z: 2 }],
  },
  {
    id: 'map-4-0', tint: 'green', mapped: true,
    exits: [{ direction: 'west', target: 'map-3-0' }, { direction: 'east', target: 'map-5-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 2, z: 3, height: 2 }, { x: 2, z: 4, height: 2 }, { x: 5, z: 3, height: 2 }, { x: 5, z: 4, height: 2 }],
    spikes: [{ x: 2, z: 2 }, { x: 2, z: 5 }, { x: 5, z: 2 }, { x: 5, z: 5 }],
    pathGuards: [{ path: [{ x: 3, z: 3 }, { x: 4, z: 3 }, { x: 4, z: 4 }, { x: 3, z: 4 }] }],
  },
  {
    id: 'map--1--4', tint: 'blue', mapped: true,
    exits: [{ direction: 'south', target: 'map--1--3' }, { direction: 'north', target: 'map--1--5' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    ghosts: [{ x: 6, z: 4 }],
  },
  {
    id: 'map--1-4', tint: 'purple', mapped: true,
    exits: [{ direction: 'north', target: 'map--1-3' }, { direction: 'west', target: 'map--2-4' }, { direction: 'south', target: 'map--1-5' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 6, z: 5, height: 1 }, { x: 6, z: 6, height: 1 }],
    pickups: [{ x: 3, z: 3, item: 'wine-bottle' }],
  },
  {
    id: 'map--4-1', tint: 'green', mapped: true,
    exits: [{ direction: 'east', target: 'map--3-1' }, { direction: 'south', target: 'map--4-2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 0, z: 0, height: 3 }, { x: 1, z: 0, height: 3 }, { x: 0, z: 1, height: 3 }, { x: 1, z: 1, height: 3 }, { x: 2, z: 0, height: 2 }, { x: 0, z: 2, height: 2 }, { x: 2, z: 1, height: 2 }, { x: 1, z: 2, height: 2 }],
    pickups: [{ x: 3, z: 3, item: 'crystal-ball' }],
  },
  {
    id: 'map--5-0', tint: 'yellow', mapped: true,
    exits: [{ direction: 'east', target: 'map--4-0' }, { direction: 'north', target: 'map--5--1' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map-3--2', tint: 'blue', mapped: true,
    exits: [{ direction: 'east', target: 'map-4--2' }, { direction: 'south', target: 'map-3--1' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 2, height: 3 }, { x: 3, z: 4, height: 3 }],
    spikes: [{ x: 4, z: 2 }, { x: 4, z: 3 }, { x: 4, z: 4 }],
  },
  {
    id: 'map-3-2', tint: 'green', mapped: true,
    exits: [{ direction: 'west', target: 'map-2-2' }, { direction: 'east', target: 'map-4-2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 4, z: 3, height: 2 }, { x: 4, z: 4, height: 2 }],
    flames: [{ x: 3, z: 1, height: 0 }, { x: 4, z: 2, height: 0 }],
  },
  {
    id: 'map-4--1', tint: 'green', mapped: true,
    exits: [{ direction: 'west', target: 'map-3--1' }, { direction: 'north', target: 'map-4--2' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map-5-0', tint: 'blue', mapped: true,
    exits: [{ direction: 'west', target: 'map-4-0' }, { direction: 'east', target: 'map-6-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    spikes: [{ x: 4, z: 3 }],
  },
  {
    id: 'map--1--5', tint: 'purple', mapped: true,
    exits: [{ direction: 'south', target: 'map--1--4' }],
    spawn: { x: 3, z: 1 },
    platforms: [],
    flames: [{ x: 2, z: 3, height: 0 }, { x: 4, z: 1, height: 0 }],
  },
  {
    id: 'map--1-5', tint: 'green', mapped: true,
    exits: [{ direction: 'north', target: 'map--1-4' }, { direction: 'south', target: 'map--1-6' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    tables: [{ x: 2, z: 2, height: 1 }],
    pickups: [{ x: 3, z: 3, item: 'poison' }],
  },
  {
    id: 'map--2-4', tint: 'yellow', mapped: true,
    exits: [{ direction: 'west', target: 'map--3-4' }, { direction: 'east', target: 'map--1-4' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 4, z: 3, height: 4 }, { x: 4, z: 4, height: 4 }, { x: 4, z: 5, height: 2 }],
    pickups: [{ x: 3, z: 3, item: 'boot' }],
  },
  {
    id: 'map--4-2', tint: 'yellow', mapped: true,
    exits: [{ direction: 'south', target: 'map--4-3' }, { direction: 'north', target: 'map--4-1' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 4, z: 2, height: 1 }, { x: 4, z: 6, height: 1 }],
    pickups: [{ x: 3, z: 3, item: 'teacup' }],
  },
  {
    id: 'map--5--1', tint: 'green', mapped: true,
    exits: [{ direction: 'south', target: 'map--5-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 2, z: 4, height: 3 }, { x: 3, z: 4, height: 1 }, { x: 4, z: 4, height: 1 }, { x: 5, z: 4, height: 3 }],
    flames: [{ x: 3, z: 4, height: 1 }],
  },
  {
    id: 'map-4--2', tint: 'yellow', mapped: true,
    exits: [{ direction: 'south', target: 'map-4--1' }, { direction: 'west', target: 'map-3--2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 1, z: 2, height: 2 }],
    pickups: [{ x: 3, z: 3, item: 'crystal-ball' }],
  },
  {
    id: 'map-4-2', tint: 'purple', mapped: true,
    exits: [{ direction: 'west', target: 'map-3-2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 2, height: 2 }, { x: 3, z: 3, height: 2 }, { x: 3, z: 4, height: 2 }, { x: 3, z: 5, height: 2 }],
    pickups: [{ x: 4, z: 3, item: 'life' }],
  },
  {
    id: 'map-6-0', tint: 'purple', mapped: true,
    exits: [{ direction: 'west', target: 'map-5-0' }, { direction: 'east', target: 'map-7-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    tables: [{ x: 2, z: 2, height: 1 }, { x: 3, z: 4, height: 1 }],
    ghosts: [{ x: 5, z: 4 }],
    pickups: [{ x: 3, z: 3, item: 'wine-bottle' }],
  },
  {
    id: 'map--1-6', tint: 'blue', mapped: true,
    exits: [{ direction: 'north', target: 'map--1-5' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    spikes: [{ x: 2, z: 2 }, { x: 3, z: 2 }, { x: 4, z: 2 }, { x: 5, z: 2 }, { x: 2, z: 5 }, { x: 3, z: 5 }, { x: 4, z: 5 }, { x: 5, z: 5 }],
    balls: [{ from: { x: 2, z: 3 }, to: { x: 5, z: 3 } }],
    pickups: [{ x: 3, z: 4, item: 'life' }],
  },
  {
    id: 'map--3-4', tint: 'blue', mapped: true,
    exits: [{ direction: 'west', target: 'map--4-4' }, { direction: 'east', target: 'map--2-4' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 4, z: 4, height: 3 }, { x: 3, z: 5, height: 2 }, { x: 5, z: 3, height: 2 }, { x: 4, z: 5, height: 2 }, { x: 5, z: 4, height: 2 }, { x: 5, z: 5, height: 2 }],
  },
  {
    id: 'map--4-3', tint: 'blue', mapped: true,
    exits: [{ direction: 'south', target: 'map--4-4' }, { direction: 'north', target: 'map--4-2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 1, height: 1 }],
    spikes: [{ x: 1, z: 3 }, { x: 2, z: 4 }, { x: 4, z: 2 }, { x: 5, z: 3 }],
  },
  {
    id: 'map-7-0', tint: 'yellow', mapped: true,
    exits: [{ direction: 'north', target: 'map-7--1' }, { direction: 'west', target: 'map-6-0' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map--4-4', tint: 'green', mapped: true,
    exits: [{ direction: 'west', target: 'map--5-4' }, { direction: 'east', target: 'map--3-4' }, { direction: 'south', target: 'map--4-5' }, { direction: 'north', target: 'map--4-3' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map-7--1', tint: 'blue', mapped: true,
    exits: [{ direction: 'south', target: 'map-7-0' }, { direction: 'north', target: 'map-7--2' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 1, z: 3, height: 3 }, { x: 2, z: 3, height: 3 }, { x: 3, z: 3, height: 3 }, { x: 4, z: 3, height: 3 }],
    pickups: [{ x: 3, z: 4, item: 'goblet' }],
  },
  {
    id: 'map--4-5', tint: 'yellow', mapped: true,
    exits: [{ direction: 'south', target: 'map--4-6' }, { direction: 'north', target: 'map--4-4' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    spikes: [{ x: 0, z: 4 }, { x: 1, z: 4 }, { x: 2, z: 4 }, { x: 3, z: 4 }, { x: 4, z: 4 }, { x: 5, z: 4 }, { x: 6, z: 4 }, { x: 7, z: 4 }],
  },
  {
    id: 'map--5-4', tint: 'yellow', mapped: true,
    exits: [{ direction: 'west', target: 'map--6-4' }, { direction: 'east', target: 'map--4-4' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 2, z: 4, height: 2 }, { x: 5, z: 3, height: 2 }, { x: 5, z: 4, height: 2 }, { x: 6, z: 4, height: 1 }],
    spikes: [{ x: 3, z: 1 }, { x: 3, z: 2 }, { x: 3, z: 4 }, { x: 3, z: 5 }],
    balls: [{ from: { x: 1, z: 2 }, to: { x: 6, z: 2 } }],
  },
  {
    id: 'map-7--2', tint: 'green', mapped: true,
    exits: [{ direction: 'south', target: 'map-7--1' }, { direction: 'north', target: 'map-7--3' }],
    spawn: { x: 3, z: 1 },
    platforms: [{ x: 3, z: 4, height: 1 }, { x: 4, z: 4, height: 1 }, { x: 4, z: 1, height: 1 }],
  },
  {
    id: 'map--4-6', tint: 'purple', mapped: true,
    exits: [{ direction: 'south', target: 'map--4-7' }, { direction: 'north', target: 'map--4-5' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    spikes: [{ x: 0, z: 2 }, { x: 0, z: 5 }, { x: 1, z: 4 }, { x: 2, z: 0 }, { x: 2, z: 2 }, { x: 3, z: 4 }, { x: 4, z: 2 }, { x: 4, z: 4 }, { x: 5, z: 5 }, { x: 6, z: 2 }, { x: 7, z: 4 }, { x: 7, z: 6 }],
  },
  {
    id: 'map--6-4', tint: 'blue', mapped: true,
    exits: [{ direction: 'west', target: 'map--7-4' }, { direction: 'east', target: 'map--5-4' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 4, height: 1 }, { x: 3, z: 3, height: 2 }],
    spikes: [{ x: 2, z: 4 }, { x: 2, z: 5 }, { x: 4, z: 2 }, { x: 4, z: 5 }, { x: 5, z: 3 }, { x: 5, z: 4 }],
  },
  {
    id: 'map-7--3', tint: 'purple', mapped: true,
    exits: [{ direction: 'south', target: 'map-7--2' }, { direction: 'north', target: 'map-7--4' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 6, z: 0, height: 3 }, { x: 7, z: 0, height: 3 }],
    spikes: [{ x: 5, z: 2 }, { x: 5, z: 3 }, { x: 5, z: 4 }, { x: 5, z: 5 }],
    pickups: [{ x: 3, z: 3, item: 'gem' }],
  },
  {
    id: 'map--4-7', tint: 'yellow', mapped: true,
    exits: [{ direction: 'north', target: 'map--4-6' }, { direction: 'south', target: 'map--4-8' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
  },
  {
    id: 'map--7-4', tint: 'green', mapped: true,
    exits: [{ direction: 'east', target: 'map--6-4' }, { direction: 'west', target: 'map--8-4' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 2, z: 2, height: 1 }, { x: 4, z: 2, height: 1 }, { x: 6, z: 2, height: 1 }, { x: 2, z: 5, height: 1 }, { x: 4, z: 5, height: 1 }, { x: 6, z: 5, height: 1 }],
    flames: [{ x: 3, z: 3, height: 0 }, { x: 5, z: 3, height: 0 }],
  },
  {
    id: 'map-7--4', tint: 'green', mapped: true,
    exits: [{ direction: 'south', target: 'map-7--3' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    ghosts: [{ x: 3, z: 2 }],
  },
  {
    id: 'map--4-8', tint: 'blue', mapped: true,
    exits: [{ direction: 'west', target: 'map--5-8' }, { direction: 'north', target: 'map--4-7' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 5, height: 2 }, { x: 4, z: 4, height: 2 }, { x: 2, z: 3, height: 3 }],
  },
  {
    id: 'map--8-4', tint: 'blue', mapped: true,
    exits: [{ direction: 'east', target: 'map--7-4' }, { direction: 'south', target: 'map--8-5' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    pathGuards: [{ path: [{ x: 3, z: 5 }, { x: 0, z: 5 }] }],
    pickups: [{ x: 3, z: 3, item: 'teacup' }],
  },
  {
    id: 'map--5-8', tint: 'yellow', mapped: true,
    exits: [{ direction: 'east', target: 'map--4-8' }],
    spawn: { x: 4, z: 1 },
    platforms: [{ x: 3, z: 3, height: 2 }, { x: 3, z: 4, height: 2 }, { x: 4, z: 3, height: 2 }, { x: 4, z: 4, height: 2 }, { x: 5, z: 3, height: 1 }, { x: 5, z: 4, height: 1 }],
  },
  {
    id: 'map--8-5', tint: 'blue', mapped: true,
    exits: [{ direction: 'south', target: 'map--8-6' }, { direction: 'north', target: 'map--8-4' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    spikes: [{ x: 2, z: 2 }, { x: 2, z: 3 }, { x: 2, z: 4 }, { x: 2, z: 5 }, { x: 5, z: 2 }, { x: 5, z: 3 }, { x: 5, z: 4 }, { x: 5, z: 5 }],
  },
  {
    id: 'map--8-6', tint: 'purple', mapped: true,
    exits: [{ direction: 'east', target: 'map--7-6' }, { direction: 'north', target: 'map--8-5' }],
    spawn: { x: 4, z: 1 },
    platforms: [],
    pickups: [{ x: 3, z: 3, item: 'boot' }],
  },
  {
    id: 'map--7-6', tint: 'yellow', mapped: true,
    exits: [{ direction: 'west', target: 'map--8-6' }, { direction: 'east', target: 'map--6-6' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    balls: [{ from: { x: 1, z: 1 }, to: { x: 6, z: 1 } }],
  },
  {
    id: 'map--6-6', tint: 'purple', mapped: true,
    exits: [{ direction: 'west', target: 'map--7-6' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 1, height: 1 }],
    spikes: [{ x: 1, z: 0 }, { x: 2, z: 0 }, { x: 3, z: 1 }, { x: 3, z: 2 }, { x: 3, z: 3 }, { x: 4, z: 1 }, { x: 4, z: 2 }, { x: 4, z: 3 }, { x: 5, z: 0 }, { x: 6, z: 0 }, { x: 7, z: 0 }],
    pickups: [{ x: 3, z: 4, item: 'poison' }],
  },
]
