import type { RoomTint } from './shell'
import type { ItemId } from './items'

// Data-driven rooms. A spec is pure data (unit-tested for map integrity);
// buildRoomFromSpec turns it into a Room. Cells are 0..7 on the 8x8 grid.
// Doorways sit mid-edge: north (4,0), south (4,7), west (0,4), east (7,4).

export type Direction = 'north' | 'south' | 'east' | 'west'

export interface Cell {
  x: number
  z: number
}

export interface RoomSpec {
  id: string
  tint: RoomTint
  // Cells across (x) and deep (z); the original's narrow rooms are 4 on one axis.
  width?: number
  depth?: number
  exits: { direction: Direction; target: string }[]
  spawn: Cell
  platforms?: (Cell & { height: number })[]
  pushBlocks?: Cell[]
  // A spike with a height sits on top of a block that tall.
  spikes?: (Cell & { height?: number })[]
  spikedBalls?: (Cell & { height: number; bobs?: boolean })[]
  // Not every door can be reached from every other on foot: it takes a
  // charm to stand on, or a block to push. Tests and the bot go round these.
  puzzle?: boolean
  // Blocks hanging in the air: `bottom` is the underside, in blocks.
  floatingBlocks?: (Cell & { bottom: number })[]
  guards?: { from: Cell; to: Cell; speed?: number }[]
  ghosts?: Cell[]
  pickups?: (Cell & { item: ItemId; y?: number })[]
  movingPlatforms?: { from: Cell; to: Cell; height: number }[]
  pathGuards?: { path: Cell[] }[]
  tables?: (Cell & { height: number })[]
  vanishing?: (Cell & { height: number })[]
  balls?: { from: Cell; to: Cell }[]
  cauldron?: Cell & { height: number }
  wizard?: Cell
  flames?: (Cell & { height: number })[]
  // Grilles that rise and fall across a line of cells (see Portcullis).
  portcullises?: { from: Cell; to: Cell }[]
  // Read off map.png (tools/map): doors, blocks, spike beds, some furniture.
  mapped?: boolean
}

const OPPOSITE: Record<Direction, Direction> = { north: 'south', south: 'north', east: 'west', west: 'east' }

export function oppositeOf(direction: Direction): Direction {
  return OPPOSITE[direction]
}

export const FULL_SIZE = 8
const TILE_UNITS = 2

// A doorway is the middle cell of its edge.
export function doorCell(direction: Direction, width = FULL_SIZE, depth = FULL_SIZE): Cell {
  const midX = Math.floor(width / 2)
  const midZ = Math.floor(depth / 2)
  switch (direction) {
    case 'north': return { x: midX, z: 0 }
    case 'south': return { x: midX, z: depth - 1 }
    case 'west': return { x: 0, z: midZ }
    case 'east': return { x: width - 1, z: midZ }
  }
}

// Walking out through a door lands you just inside the opposite edge of the
// room you enter, on its door axis (width and depth are that room's).
export function entryFor(direction: Direction, width = FULL_SIZE, depth = FULL_SIZE): { x: number; z: number } {
  const axisX = Math.floor(width / 2) * TILE_UNITS + TILE_UNITS / 2
  const axisZ = Math.floor(depth / 2) * TILE_UNITS + TILE_UNITS / 2
  switch (direction) {
    case 'south': return { x: axisX, z: 1 }
    case 'north': return { x: axisX, z: depth * TILE_UNITS - 1 }
    case 'east': return { x: 1, z: axisZ }
    case 'west': return { x: width * TILE_UNITS - 1, z: axisZ }
  }
}

export const LEGACY_ROOM_LINKS: { id: string; exits: { direction: Direction; target: string }[] }[] = []

// Generated by tools/rip/castle.py from the original's room table. Do not
// edit here: change the generator and run it again.
export const START_ROOMS = ['map-7--6', 'map--4--4', 'map--5-3', 'map-7-0']

export const ROOM_SPECS: RoomSpec[] = [
  {
    id: 'map--8--8', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--8--7' }, { direction: 'east', target: 'map--7--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 2, height: 3 }, { x: 1, z: 2, height: 3 }, { x: 2, z: 0, height: 3 }, { x: 2, z: 1, height: 3 }],
    floatingBlocks: [{ x: 0, z: 0, bottom: 3 }, { x: 0, z: 1, bottom: 3 }, { x: 1, z: 0, bottom: 3 }],
    vanishing: [{ x: 1, z: 1, height: 4 }],
  },
  {
    id: 'map--7--8', tint: 'green', depth: 4,
    exits: [{ direction: 'east', target: 'map--6--8' }, { direction: 'west', target: 'map--8--8' }],
    spawn: { x: 5, z: 0 },
    platforms: [{ x: 3, z: 0, height: 2 }, { x: 3, z: 3, height: 2 }, { x: 4, z: 0, height: 2 }, { x: 4, z: 3, height: 2 }],
    pathGuards: [{ path: [{ x: 2, z: 1 }, { x: 5, z: 1 }] }],
    ghosts: [{ x: 2, z: 2 }],
  },
  {
    id: 'map--6--8', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--6--7' }, { direction: 'east', target: 'map--5--8' }, { direction: 'west', target: 'map--7--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--5--8', tint: 'yellow', depth: 4,
    exits: [{ direction: 'east', target: 'map--4--8' }, { direction: 'west', target: 'map--6--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 1, height: 1 }, { x: 2, z: 2, height: 1 }, { x: 5, z: 1, height: 1 }, { x: 5, z: 2, height: 1 }],
    spikes: [{ x: 3, z: 2 }, { x: 3, z: 1 }, { x: 4, z: 2 }, { x: 4, z: 1 }],
    vanishing: [{ x: 3, z: 2, height: 2 }, { x: 4, z: 2, height: 2 }, { x: 3, z: 1, height: 2 }, { x: 4, z: 1, height: 2 }],
    spikedBalls: [{ x: 3, z: 3, height: 0 }, { x: 4, z: 3, height: 0 }, { x: 3, z: 0, height: 0 }, { x: 4, z: 0, height: 0 }],
  },
  {
    id: 'map--4--8', tint: 'cyan',
    exits: [{ direction: 'south', target: 'map--4--7' }, { direction: 'west', target: 'map--5--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 3, z: 3, bottom: 2 }, { x: 3, z: 3, bottom: 3 }, { x: 3, z: 4, bottom: 1 }],
    spikes: [{ x: 3, z: 4 }, { x: 2, z: 3 }, { x: 4, z: 3 }, { x: 3, z: 2 }],
    vanishing: [{ x: 2, z: 3, height: 2 }, { x: 4, z: 3, height: 2 }, { x: 3, z: 2, height: 2 }],
  },
  {
    id: 'map-0--8', tint: 'purple',
    exits: [{ direction: 'south', target: 'map-0--7' }, { direction: 'east', target: 'map-1--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 3, height: 4 }],
    floatingBlocks: [{ x: 1, z: 1, bottom: 1 }],
    spikes: [{ x: 3, z: 4 }, { x: 2, z: 3 }, { x: 4, z: 3 }, { x: 3, z: 2 }],
    balls: [{ from: { x: 1, z: 1 }, to: { x: 1, z: 1 } }],
    spikedBalls: [{ x: 3, z: 4, height: 1 }, { x: 2, z: 3, height: 1 }, { x: 4, z: 3, height: 1 }, { x: 3, z: 2, height: 1 }],
  },
  {
    id: 'map-1--8', tint: 'yellow',
    exits: [{ direction: 'east', target: 'map-2--8' }, { direction: 'west', target: 'map-0--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    ghosts: [{ x: 3, z: 4 }],
    pickups: [{ x: 3, z: 3, item: 'teacup' }],
  },
  {
    id: 'map-2--8', tint: 'purple',
    exits: [{ direction: 'east', target: 'map-3--8' }, { direction: 'west', target: 'map-1--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 4, height: 3 }, { x: 4, z: 4, height: 3 }],
    spikes: [{ x: 2, z: 5 }, { x: 3, z: 5 }, { x: 3, z: 5, height: 1 }, { x: 4, z: 5 }, { x: 2, z: 3 }, { x: 3, z: 3 }, { x: 3, z: 3, height: 1 }, { x: 4, z: 3 }],
    tables: [{ x: 6, z: 1, height: 1 }],
    pickups: [{ x: 3, z: 2, item: 'boot' }],
  },
  {
    id: 'map-3--8', tint: 'yellow',
    exits: [{ direction: 'east', target: 'map-4--8' }, { direction: 'west', target: 'map-2--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    pickups: [{ x: 3, z: 3, item: 'crystal-ball' }],
  },
  {
    id: 'map-4--8', tint: 'purple',
    exits: [{ direction: 'east', target: 'map-5--8' }, { direction: 'west', target: 'map-3--8' }],
    spawn: { x: 3, z: 0 },
    platforms: [],
    spikes: [{ x: 5, z: 7 }, { x: 2, z: 6 }, { x: 0, z: 5 }, { x: 4, z: 5 }, { x: 7, z: 5 }, { x: 2, z: 4 }, { x: 4, z: 3 }, { x: 0, z: 2 }, { x: 2, z: 2 }, { x: 7, z: 2 }, { x: 5, z: 1 }, { x: 4, z: 0 }],
    balls: [{ from: { x: 4, z: 4 }, to: { x: 4, z: 4 } }],
  },
  {
    id: 'map-5--8', tint: 'green',
    exits: [{ direction: 'south', target: 'map-5--7' }, { direction: 'east', target: 'map-6--8' }, { direction: 'west', target: 'map-4--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    pickups: [{ x: 3, z: 3, item: 'wine-bottle' }],
  },
  {
    id: 'map-6--8', tint: 'cyan', depth: 4,
    exits: [{ direction: 'east', target: 'map-7--8' }, { direction: 'west', target: 'map-5--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    flames: [{ x: 2, z: 0, height: 0 }, { x: 5, z: 1, height: 0 }, { x: 4, z: 3, height: 0 }, { x: 3, z: 2, height: 0 }],
    pickups: [{ x: 3, z: 1, item: 'gem' }],
  },
  {
    id: 'map-7--8', tint: 'green',
    exits: [{ direction: 'south', target: 'map-7--7' }, { direction: 'west', target: 'map-6--8' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 2, height: 2 }, { x: 3, z: 4, height: 2 }, { x: 4, z: 3, height: 1 }, { x: 5, z: 2, height: 2 }, { x: 5, z: 4, height: 2 }],
    floatingBlocks: [{ x: 3, z: 3, bottom: 1 }, { x: 4, z: 2, bottom: 1 }, { x: 4, z: 4, bottom: 1 }, { x: 5, z: 3, bottom: 1 }],
    vanishing: [{ x: 4, z: 3, height: 3 }],
    spikedBalls: [{ x: 4, z: 4, height: 2, bobs: true }, { x: 3, z: 3, height: 2, bobs: true }, { x: 5, z: 3, height: 2, bobs: true }, { x: 4, z: 2, height: 2, bobs: true }],
    pickups: [{ x: 2, z: 3, item: 'goblet' }],
  },
  {
    id: 'map--8--7', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map--8--6' }, { direction: 'north', target: 'map--8--8' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 1, height: 1 }, { x: 1, z: 1, height: 1 }, { x: 2, z: 1, height: 1 }, { x: 3, z: 0, height: 1 }],
    floatingBlocks: [{ x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }],
    vanishing: [{ x: 0, z: 0, height: 4 }],
    spikedBalls: [{ x: 3, z: 0, height: 1, bobs: true }, { x: 2, z: 1, height: 1, bobs: true }, { x: 1, z: 1, height: 1, bobs: true }, { x: 0, z: 1, height: 1, bobs: true }],
    flames: [{ x: 0, z: 3, height: 1 }],
    puzzle: true,
  },
  {
    id: 'map--6--7', tint: 'green', width: 4,
    exits: [{ direction: 'south', target: 'map--6--6' }, { direction: 'north', target: 'map--6--8' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    spikedBalls: [{ x: 0, z: 7, height: 3 }, { x: 3, z: 7, height: 3 }, { x: 1, z: 6, height: 3 }, { x: 2, z: 6, height: 3 }, { x: 1, z: 5, height: 3 }, { x: 2, z: 5, height: 3 }, { x: 1, z: 4, height: 3 }, { x: 2, z: 4, height: 3 }, { x: 1, z: 3, height: 3 }, { x: 2, z: 3, height: 3 }, { x: 1, z: 2, height: 3 }, { x: 2, z: 2, height: 3 }, { x: 1, z: 1, height: 3 }, { x: 2, z: 1, height: 3 }, { x: 0, z: 0, height: 3 }, { x: 3, z: 0, height: 3 }],
  },
  {
    id: 'map--4--7', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map--4--6' }, { direction: 'north', target: 'map--4--8' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }],
    spikes: [{ x: 1, z: 1 }, { x: 2, z: 1 }],
    vanishing: [{ x: 0, z: 0, height: 4 }, { x: 0, z: 1, height: 4 }, { x: 0, z: 2, height: 4 }, { x: 0, z: 3, height: 4 }, { x: 1, z: 3, height: 4 }, { x: 2, z: 3, height: 4 }, { x: 3, z: 3, height: 4 }, { x: 3, z: 4, height: 4 }, { x: 3, z: 5, height: 3 }, { x: 3, z: 6, height: 2 }, { x: 3, z: 7, height: 1 }],
  },
  {
    id: 'map-0--7', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map-0--6' }, { direction: 'north', target: 'map-0--8' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    spikes: [{ x: 0, z: 5 }, { x: 1, z: 5 }, { x: 2, z: 5 }, { x: 3, z: 5 }, { x: 0, z: 2 }, { x: 1, z: 2 }, { x: 2, z: 2 }, { x: 3, z: 2 }],
    balls: [{ from: { x: 1, z: 3 }, to: { x: 1, z: 3 } }],
  },
  {
    id: 'map-5--7', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map-5--6' }, { direction: 'north', target: 'map-5--8' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 2, z: 1, height: 4 }, { x: 2, z: 2, height: 2 }, { x: 2, z: 4, height: 2 }, { x: 2, z: 5, height: 2 }, { x: 2, z: 6, height: 1 }],
    floatingBlocks: [{ x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }],
    spikes: [{ x: 2, z: 2 }, { x: 2, z: 3 }],
  },
  {
    id: 'map-7--7', tint: 'purple', width: 4,
    exits: [{ direction: 'south', target: 'map-7--6' }, { direction: 'north', target: 'map-7--8' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 2, height: 1 }, { x: 0, z: 5, height: 1 }, { x: 3, z: 2, height: 1 }, { x: 3, z: 5, height: 1 }],
    spikes: [{ x: 0, z: 2, height: 1 }, { x: 1, z: 2 }, { x: 2, z: 2 }, { x: 3, z: 2, height: 1 }, { x: 0, z: 5, height: 1 }, { x: 1, z: 5 }, { x: 2, z: 5 }, { x: 3, z: 5, height: 1 }],
    balls: [{ from: { x: 1, z: 2 }, to: { x: 1, z: 2 } }, { from: { x: 1, z: 5 }, to: { x: 1, z: 5 } }],
  },
  {
    id: 'map--8--6', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--8--5' }, { direction: 'east', target: 'map--7--6' }, { direction: 'north', target: 'map--8--7' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 3, height: 1 }],
    floatingBlocks: [{ x: 3, z: 0, bottom: 3 }, { x: 4, z: 0, bottom: 3 }],
    spikes: [{ x: 2, z: 0 }],
    vanishing: [{ x: 0, z: 2, height: 2 }, { x: 0, z: 1, height: 3 }, { x: 0, z: 0, height: 4 }],
  },
  {
    id: 'map--7--6', tint: 'yellow', depth: 4,
    exits: [{ direction: 'east', target: 'map--6--6' }, { direction: 'west', target: 'map--8--6' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 1, z: 2, height: 2 }, { x: 4, z: 2, height: 2 }, { x: 5, z: 2, height: 2 }, { x: 6, z: 2, height: 2 }],
    floatingBlocks: [{ x: 2, z: 2, bottom: 2 }, { x: 2, z: 2, bottom: 3 }, { x: 3, z: 2, bottom: 2 }, { x: 7, z: 1, bottom: 3 }, { x: 7, z: 2, bottom: 3 }],
    spikes: [{ x: 4, z: 2, height: 2 }, { x: 6, z: 2, height: 2 }],
    balls: [{ from: { x: 5, z: 2 }, to: { x: 5, z: 2 } }],
  },
  {
    id: 'map--6--6', tint: 'purple',
    exits: [{ direction: 'north', target: 'map--6--7' }, { direction: 'west', target: 'map--7--6' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 6, height: 1 }],
    floatingBlocks: [{ x: 0, z: 7, bottom: 1 }, { x: 1, z: 7, bottom: 2 }, { x: 2, z: 7, bottom: 3 }],
    spikes: [{ x: 1, z: 7 }, { x: 2, z: 7 }, { x: 5, z: 7 }, { x: 6, z: 7 }, { x: 7, z: 7 }, { x: 3, z: 6 }, { x: 3, z: 5 }, { x: 3, z: 4 }, { x: 4, z: 6 }, { x: 4, z: 5 }, { x: 4, z: 4 }],
    vanishing: [{ x: 3, z: 7, height: 4 }],
  },
  {
    id: 'map--4--6', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--4--5' }, { direction: 'north', target: 'map--4--7' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    spikes: [{ x: 2, z: 0 }, { x: 5, z: 0 }, { x: 2, z: 1 }, { x: 7, z: 1 }, { x: 0, z: 2 }, { x: 5, z: 2 }, { x: 1, z: 3 }, { x: 3, z: 3 }, { x: 4, z: 3 }, { x: 7, z: 3 }, { x: 0, z: 5 }, { x: 2, z: 5 }, { x: 4, z: 5 }, { x: 6, z: 5 }, { x: 2, z: 7 }, { x: 5, z: 7 }],
  },
  {
    id: 'map--1--6', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map--1--5' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 3, height: 1 }, { x: 3, z: 4, height: 1 }, { x: 4, z: 3, height: 1 }, { x: 4, z: 4, height: 1 }],
    ghosts: [{ x: 2, z: 2 }, { x: 5, z: 2 }, { x: 2, z: 5 }, { x: 5, z: 5 }],
  },
  {
    id: 'map-0--6', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map-0--5' }, { direction: 'north', target: 'map-0--7' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }],
    spikes: [{ x: 1, z: 1 }, { x: 2, z: 1 }],
    tables: [{ x: 1, z: 4, height: 1 }, { x: 1, z: 4, height: 2 }],
    pickups: [{ x: 1, z: 3, item: 'gem' }],
  },
  {
    id: 'map-5--6', tint: 'green',
    exits: [{ direction: 'east', target: 'map-6--6' }, { direction: 'north', target: 'map-5--7' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 2, height: 1 }, { x: 3, z: 3, height: 2 }, { x: 3, z: 4, height: 4 }],
    floatingBlocks: [{ x: 7, z: 3, bottom: 3 }, { x: 7, z: 4, bottom: 3 }],
    spikes: [{ x: 6, z: 3 }, { x: 6, z: 4 }, { x: 2, z: 4 }, { x: 4, z: 4 }],
  },
  {
    id: 'map-6--6', tint: 'cyan', depth: 4,
    exits: [{ direction: 'east', target: 'map-7--6' }, { direction: 'west', target: 'map-5--6' }],
    spawn: { x: 5, z: 0 },
    platforms: [],
    spikes: [{ x: 3, z: 3 }, { x: 4, z: 3 }, { x: 2, z: 2 }, { x: 5, z: 2 }, { x: 2, z: 1 }, { x: 5, z: 1 }, { x: 3, z: 0 }, { x: 4, z: 0 }],
    pathGuards: [{ path: [{ x: 3, z: 2 }, { x: 4, z: 2 }] }],
  },
  {
    id: 'map-7--6', tint: 'green',
    exits: [{ direction: 'south', target: 'map-7--5' }, { direction: 'north', target: 'map-7--7' }, { direction: 'west', target: 'map-6--6' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--8--5', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map--8--4' }, { direction: 'north', target: 'map--8--6' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    spikes: [{ x: 1, z: 6 }, { x: 2, z: 6 }, { x: 0, z: 5 }, { x: 3, z: 5 }, { x: 0, z: 4 }, { x: 3, z: 4 }, { x: 0, z: 3 }, { x: 3, z: 3 }, { x: 0, z: 2 }, { x: 3, z: 2 }, { x: 1, z: 1 }, { x: 2, z: 1 }],
    balls: [{ from: { x: 1, z: 3 }, to: { x: 1, z: 3 } }],
  },
  {
    id: 'map--4--5', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map--4--4' }, { direction: 'north', target: 'map--4--6' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    tables: [{ x: 0, z: 3, height: 1 }, { x: 1, z: 3, height: 1 }, { x: 2, z: 3, height: 1 }, { x: 3, z: 3, height: 1 }, { x: 0, z: 3, height: 2 }, { x: 1, z: 3, height: 2 }, { x: 2, z: 3, height: 2 }, { x: 3, z: 3, height: 2 }],
    spikedBalls: [{ x: 0, z: 3, height: 2 }, { x: 1, z: 3, height: 2 }, { x: 2, z: 3, height: 2 }, { x: 3, z: 3, height: 2 }, { x: 0, z: 3, height: 3 }, { x: 1, z: 3, height: 3 }, { x: 2, z: 3, height: 3 }, { x: 3, z: 3, height: 3 }],
    puzzle: true,
  },
  {
    id: 'map--1--5', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map--1--4' }, { direction: 'north', target: 'map--1--6' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 2, z: 5, height: 1 }],
    movingPlatforms: [{ from: { x: 2, z: 2 }, to: { x: 2, z: 4 }, height: 1 }],
    ghosts: [{ x: 3, z: 4 }, { x: 0, z: 3 }],
  },
  {
    id: 'map-0--5', tint: 'purple', width: 4,
    exits: [{ direction: 'south', target: 'map-0--4' }, { direction: 'north', target: 'map-0--6' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 0, z: 0, bottom: 3 }, { x: 0, z: 3, bottom: 3 }, { x: 0, z: 6, bottom: 3 }, { x: 0, z: 7, bottom: 1 }, { x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }],
    spikes: [{ x: 0, z: 5 }, { x: 0, z: 4 }, { x: 0, z: 3 }, { x: 0, z: 2 }, { x: 0, z: 1 }],
    vanishing: [{ x: 0, z: 5, height: 4 }, { x: 0, z: 4, height: 4 }, { x: 0, z: 2, height: 4 }, { x: 0, z: 1, height: 4 }],
    pickups: [{ x: 1, z: 3, item: 'crystal-ball' }],
  },
  {
    id: 'map-7--5', tint: 'purple',
    exits: [{ direction: 'south', target: 'map-7--4' }, { direction: 'north', target: 'map-7--6' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 3, height: 1 }, { x: 1, z: 3, height: 1 }, { x: 2, z: 3, height: 2 }, { x: 5, z: 3, height: 2 }, { x: 6, z: 3, height: 1 }, { x: 7, z: 3, height: 1 }],
    spikes: [{ x: 0, z: 3, height: 1 }, { x: 1, z: 3, height: 1 }, { x: 2, z: 3, height: 2 }, { x: 5, z: 3, height: 2 }, { x: 6, z: 3, height: 1 }, { x: 7, z: 3, height: 1 }],
    portcullises: [{ from: { x: 3, z: 3 }, to: { x: 4, z: 3 } }],
  },
  {
    id: 'map--8--4', tint: 'yellow',
    exits: [{ direction: 'east', target: 'map--7--4' }, { direction: 'north', target: 'map--8--5' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 6, z: 0, height: 1 }, { x: 7, z: 7, height: 1 }],
    floatingBlocks: [{ x: 0, z: 7, bottom: 2 }, { x: 3, z: 0, bottom: 3 }, { x: 4, z: 0, bottom: 3 }, { x: 7, z: 3, bottom: 3 }, { x: 7, z: 4, bottom: 3 }],
    pathGuards: [{ path: [{ x: 0, z: 7 }, { x: 6, z: 7 }] }],
  },
  {
    id: 'map--7--4', tint: 'green', depth: 4,
    exits: [{ direction: 'east', target: 'map--6--4' }, { direction: 'west', target: 'map--8--4' }],
    spawn: { x: 3, z: 0 },
    platforms: [{ x: 2, z: 0, height: 2 }, { x: 2, z: 3, height: 2 }, { x: 4, z: 0, height: 2 }, { x: 4, z: 3, height: 2 }, { x: 6, z: 0, height: 2 }, { x: 6, z: 3, height: 2 }],
    flames: [{ x: 5, z: 0, height: 0 }, { x: 3, z: 3, height: 0 }],
  },
  {
    id: 'map--6--4', tint: 'cyan',
    exits: [{ direction: 'east', target: 'map--5--4' }, { direction: 'west', target: 'map--7--4' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 3, height: 1 }],
    floatingBlocks: [{ x: 4, z: 3, bottom: 3 }],
    spikes: [{ x: 2, z: 2 }, { x: 2, z: 3 }, { x: 2, z: 4 }, { x: 3, z: 5 }, { x: 4, z: 5 }, { x: 5, z: 4 }, { x: 5, z: 3 }, { x: 4, z: 2 }],
    vanishing: [{ x: 3, z: 4, height: 2 }, { x: 4, z: 4, height: 3 }],
  },
  {
    id: 'map--5--4', tint: 'yellow', depth: 4,
    exits: [{ direction: 'east', target: 'map--4--4' }, { direction: 'west', target: 'map--6--4' }],
    spawn: { x: 5, z: 0 },
    platforms: [{ x: 1, z: 1, height: 1 }, { x: 1, z: 2, height: 1 }, { x: 3, z: 0, height: 1 }, { x: 3, z: 3, height: 1 }, { x: 4, z: 0, height: 1 }, { x: 4, z: 3, height: 1 }, { x: 6, z: 1, height: 1 }, { x: 6, z: 2, height: 1 }],
    floatingBlocks: [{ x: 2, z: 1, bottom: 1 }, { x: 2, z: 2, bottom: 1 }, { x: 5, z: 1, bottom: 1 }, { x: 5, z: 2, bottom: 1 }],
    spikes: [{ x: 3, z: 3, height: 1 }, { x: 4, z: 3, height: 1 }, { x: 3, z: 0, height: 1 }, { x: 4, z: 0, height: 1 }],
    balls: [{ from: { x: 2, z: 1 }, to: { x: 5, z: 1 } }],
    puzzle: true,
  },
  {
    id: 'map--4--4', tint: 'green',
    exits: [{ direction: 'south', target: 'map--4--3' }, { direction: 'east', target: 'map--3--4' }, { direction: 'north', target: 'map--4--5' }, { direction: 'west', target: 'map--5--4' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--3--4', tint: 'cyan',
    exits: [{ direction: 'east', target: 'map--2--4' }, { direction: 'west', target: 'map--4--4' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 2, height: 2 }, { x: 3, z: 4, height: 2 }, { x: 5, z: 2, height: 2 }, { x: 5, z: 4, height: 2 }],
    floatingBlocks: [{ x: 3, z: 3, bottom: 1 }, { x: 4, z: 2, bottom: 1 }, { x: 4, z: 4, bottom: 1 }, { x: 5, z: 3, bottom: 1 }],
    spikes: [{ x: 4, z: 3 }],
    vanishing: [{ x: 4, z: 3, height: 3 }],
    spikedBalls: [{ x: 4, z: 4, height: 2, bobs: true }, { x: 3, z: 3, height: 2, bobs: true }, { x: 5, z: 3, height: 2, bobs: true }, { x: 4, z: 2, height: 2, bobs: true }],
  },
  {
    id: 'map--2--4', tint: 'yellow', depth: 4,
    exits: [{ direction: 'east', target: 'map--1--4' }, { direction: 'west', target: 'map--3--4' }],
    spawn: { x: 3, z: 0 },
    platforms: [{ x: 3, z: 1, height: 2 }, { x: 3, z: 2, height: 2 }, { x: 4, z: 0, height: 2 }, { x: 4, z: 3, height: 2 }, { x: 5, z: 1, height: 2 }, { x: 5, z: 2, height: 2 }],
    vanishing: [{ x: 4, z: 2, height: 3 }, { x: 4, z: 2, height: 4 }, { x: 4, z: 1, height: 3 }, { x: 4, z: 1, height: 4 }],
    spikedBalls: [{ x: 4, z: 2, height: 0 }, { x: 4, z: 1, height: 0 }],
    puzzle: true,
  },
  {
    id: 'map--1--4', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--1--3' }, { direction: 'north', target: 'map--1--5' }, { direction: 'west', target: 'map--2--4' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-0--4', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map-0--3' }, { direction: 'north', target: 'map-0--5' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 2, z: 1, height: 3 }, { x: 2, z: 5, height: 3 }, { x: 3, z: 4, height: 1 }, { x: 3, z: 5, height: 2 }],
    floatingBlocks: [{ x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }, { x: 2, z: 1, bottom: 3 }],
    spikes: [{ x: 1, z: 1 }, { x: 2, z: 2 }],
    pickups: [{ x: 1, z: 3, item: 'teacup' }],
  },
  {
    id: 'map-7--4', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-7--3' }, { direction: 'north', target: 'map-7--5' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    spikedBalls: [{ x: 0, z: 3, height: 3, bobs: true }, { x: 1, z: 3, height: 3, bobs: true }, { x: 2, z: 3, height: 3, bobs: true }, { x: 3, z: 3, height: 3, bobs: true }, { x: 4, z: 3, height: 3, bobs: true }, { x: 5, z: 3, height: 3, bobs: true }, { x: 6, z: 3, height: 3, bobs: true }, { x: 7, z: 3, height: 3, bobs: true }, { x: 3, z: 0, height: 3, bobs: true }, { x: 4, z: 0, height: 3, bobs: true }, { x: 3, z: 7, height: 3, bobs: true }, { x: 4, z: 7, height: 3, bobs: true }],
  },
  {
    id: 'map--4--3', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map--4--2' }, { direction: 'north', target: 'map--4--4' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 1, z: 6, height: 1 }, { x: 2, z: 1, height: 1 }],
    spikes: [{ x: 0, z: 3 }, { x: 0, z: 3, height: 1 }, { x: 3, z: 4 }, { x: 3, z: 4, height: 1 }],
    movingPlatforms: [{ from: { x: 2, z: 2 }, to: { x: 2, z: 5 }, height: 1 }, { from: { x: 1, z: 2 }, to: { x: 1, z: 5 }, height: 1 }],
    spikedBalls: [{ x: 1, z: 2, height: 0 }, { x: 1, z: 1, height: 0 }, { x: 2, z: 5, height: 0 }, { x: 2, z: 4, height: 0 }],
  },
  {
    id: 'map--1--3', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map--1--2' }, { direction: 'north', target: 'map--1--4' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 2, height: 3 }, { x: 1, z: 3, height: 3 }, { x: 2, z: 4, height: 3 }, { x: 3, z: 5, height: 3 }],
    puzzle: true,
  },
  {
    id: 'map-0--3', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map-0--2' }, { direction: 'north', target: 'map-0--4' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 3, z: 3, bottom: 1 }],
    ghosts: [{ x: 3, z: 3 }],
    pickups: [{ x: 1, z: 3, item: 'life' }],
  },
  {
    id: 'map-6--3', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-6--2' }, { direction: 'east', target: 'map-7--3' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 1, z: 2, height: 1 }, { x: 1, z: 5, height: 1 }, { x: 2, z: 1, height: 1 }, { x: 2, z: 6, height: 1 }, { x: 5, z: 1, height: 1 }, { x: 5, z: 6, height: 1 }, { x: 6, z: 2, height: 1 }, { x: 6, z: 5, height: 1 }],
  },
  {
    id: 'map-7--3', tint: 'purple',
    exits: [{ direction: 'south', target: 'map-7--2' }, { direction: 'north', target: 'map-7--4' }, { direction: 'west', target: 'map-6--3' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--4--2', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map--4--1' }, { direction: 'north', target: 'map--4--3' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 1, z: 0, height: 1 }, { x: 1, z: 1, height: 1 }, { x: 1, z: 4, height: 2 }, { x: 1, z: 5, height: 1 }, { x: 2, z: 1, height: 1 }, { x: 2, z: 4, height: 1 }, { x: 2, z: 5, height: 1 }],
  },
  {
    id: 'map--1--2', tint: 'green', width: 4,
    exits: [{ direction: 'south', target: 'map--1--1' }, { direction: 'north', target: 'map--1--3' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 5, height: 1 }, { x: 3, z: 5, height: 1 }],
    spikes: [{ x: 0, z: 5, height: 1 }, { x: 3, z: 5, height: 1 }, { x: 0, z: 3 }, { x: 3, z: 3 }],
    portcullises: [{ from: { x: 0, z: 5 }, to: { x: 3, z: 5 } }],
    pathGuards: [{ path: [{ x: 0, z: 4 }, { x: 3, z: 4 }] }],
  },
  {
    id: 'map-0--2', tint: 'purple', width: 4,
    exits: [{ direction: 'south', target: 'map-0--1' }, { direction: 'north', target: 'map-0--3' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 6, height: 1 }, { x: 0, z: 7, height: 4 }, { x: 1, z: 6, height: 1 }, { x: 2, z: 6, height: 1 }, { x: 3, z: 6, height: 1 }, { x: 3, z: 7, height: 4 }],
    spikes: [{ x: 0, z: 6, height: 1 }, { x: 3, z: 6, height: 1 }],
    balls: [{ from: { x: 0, z: 4 }, to: { x: 3, z: 4 } }],
  },
  {
    id: 'map-2--2', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-2--1' }, { direction: 'east', target: 'map-3--2' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-3--2', tint: 'green', depth: 4,
    exits: [{ direction: 'east', target: 'map-4--2' }, { direction: 'west', target: 'map-2--2' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 4, z: 1, height: 2 }, { x: 4, z: 2, height: 2 }],
    floatingBlocks: [{ x: 7, z: 1, bottom: 3 }, { x: 7, z: 2, bottom: 3 }],
    flames: [{ x: 6, z: 0, height: 3 }, { x: 5, z: 3, height: 3 }],
  },
  {
    id: 'map-4--2', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map-5--2' }, { direction: 'west', target: 'map-3--2' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 0, height: 2 }, { x: 3, z: 1, height: 2 }, { x: 3, z: 2, height: 2 }, { x: 3, z: 3, height: 2 }],
    spikedBalls: [{ x: 3, z: 3, height: 2, bobs: true }, { x: 3, z: 2, height: 2, bobs: true }, { x: 3, z: 1, height: 2, bobs: true }, { x: 3, z: 0, height: 2, bobs: true }, { x: 3, z: 3, height: 3, bobs: true }, { x: 3, z: 2, height: 3, bobs: true }, { x: 3, z: 1, height: 3, bobs: true }, { x: 3, z: 0, height: 3, bobs: true }],
    puzzle: true,
  },
  {
    id: 'map-5--2', tint: 'yellow',
    exits: [{ direction: 'east', target: 'map-6--2' }, { direction: 'west', target: 'map-4--2' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 4, z: 2, height: 4 }, { x: 4, z: 5, height: 4 }],
    floatingBlocks: [{ x: 4, z: 3, bottom: 2 }, { x: 4, z: 4, bottom: 2 }],
    tables: [{ x: 1, z: 1, height: 1 }],
    pathGuards: [{ path: [{ x: 2, z: 4 }, { x: 5, z: 4 }] }],
    pickups: [{ x: 3, z: 3, item: 'goblet' }],
  },
  {
    id: 'map-6--2', tint: 'purple',
    exits: [{ direction: 'east', target: 'map-7--2' }, { direction: 'north', target: 'map-6--3' }, { direction: 'west', target: 'map-5--2' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    pickups: [{ x: 3, z: 3, item: 'life' }],
  },
  {
    id: 'map-7--2', tint: 'yellow',
    exits: [{ direction: 'north', target: 'map-7--3' }, { direction: 'west', target: 'map-6--2' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 5, z: 5, height: 2 }, { x: 6, z: 5, height: 2 }, { x: 7, z: 5, height: 2 }],
    spikedBalls: [{ x: 5, z: 7, height: 0, bobs: true }, { x: 5, z: 6, height: 0, bobs: true }, { x: 5, z: 7, height: 1, bobs: true }, { x: 5, z: 6, height: 1, bobs: true }],
    pickups: [{ x: 3, z: 3, item: 'poison' }],
  },
  {
    id: 'map--4--1', tint: 'green',
    exits: [{ direction: 'east', target: 'map--3--1' }, { direction: 'north', target: 'map--4--2' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 5, height: 2 }, { x: 1, z: 5, height: 2 }, { x: 2, z: 6, height: 2 }, { x: 2, z: 7, height: 2 }],
    spikes: [{ x: 1, z: 7 }, { x: 0, z: 6 }, { x: 1, z: 6 }],
    vanishing: [{ x: 0, z: 7, height: 3 }, { x: 1, z: 7, height: 3 }, { x: 0, z: 6, height: 3 }, { x: 1, z: 6, height: 3 }],
  },
  {
    id: 'map--3--1', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map--2--1' }, { direction: 'west', target: 'map--4--1' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 2, height: 1 }, { x: 4, z: 1, height: 1 }],
    spikes: [{ x: 4, z: 2 }, { x: 3, z: 1 }],
  },
  {
    id: 'map--2--1', tint: 'yellow', depth: 4,
    exits: [{ direction: 'east', target: 'map--1--1' }, { direction: 'west', target: 'map--3--1' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 4, z: 3, height: 1 }],
    floatingBlocks: [{ x: 5, z: 3, bottom: 1 }, { x: 6, z: 3, bottom: 2 }, { x: 7, z: 0, bottom: 3 }, { x: 7, z: 1, bottom: 3 }, { x: 7, z: 2, bottom: 3 }, { x: 7, z: 3, bottom: 3 }],
    spikes: [{ x: 6, z: 0 }, { x: 6, z: 1 }, { x: 6, z: 2 }, { x: 5, z: 0 }, { x: 5, z: 1 }, { x: 5, z: 2 }],
    puzzle: true,
  },
  {
    id: 'map--1--1', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--1-0' }, { direction: 'east', target: 'map-0--1' }, { direction: 'north', target: 'map--1--2' }, { direction: 'west', target: 'map--2--1' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-0--1', tint: 'green',
    exits: [{ direction: 'south', target: 'room-001' }, { direction: 'east', target: 'map-1--1' }, { direction: 'north', target: 'map-0--2' }, { direction: 'west', target: 'map--1--1' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    spikes: [{ x: 1, z: 7 }, { x: 7, z: 7 }, { x: 5, z: 6 }, { x: 0, z: 5 }, { x: 4, z: 5 }, { x: 7, z: 5 }, { x: 3, z: 4 }, { x: 5, z: 3 }, { x: 1, z: 2 }, { x: 3, z: 2 }, { x: 2, z: 1 }, { x: 5, z: 1 }, { x: 6, z: 1 }],
    pathGuards: [{ path: [{ x: 4, z: 2 }, { x: 7, z: 2 }] }],
  },
  {
    id: 'map-1--1', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map-2--1' }, { direction: 'west', target: 'map-0--1' }],
    spawn: { x: 5, z: 0 },
    platforms: [],
    spikes: [{ x: 3, z: 3 }, { x: 4, z: 3 }, { x: 3, z: 2 }, { x: 4, z: 2 }, { x: 3, z: 1 }, { x: 4, z: 1 }, { x: 3, z: 0 }, { x: 4, z: 0 }],
    vanishing: [{ x: 2, z: 2, height: 1 }, { x: 2, z: 1, height: 1 }, { x: 5, z: 2, height: 1 }, { x: 5, z: 1, height: 1 }],
    balls: [{ from: { x: 2, z: 1 }, to: { x: 3, z: 1 } }],
    puzzle: true,
  },
  {
    id: 'map-2--1', tint: 'cyan',
    exits: [{ direction: 'north', target: 'map-2--2' }, { direction: 'west', target: 'map-1--1' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 5, height: 1 }],
    floatingBlocks: [{ x: 0, z: 6, bottom: 1 }, { x: 0, z: 7, bottom: 2 }, { x: 1, z: 7, bottom: 2 }, { x: 7, z: 7, bottom: 3 }],
    spikes: [{ x: 2, z: 7, height: 2 }, { x: 4, z: 7, height: 2 }, { x: 6, z: 7, height: 2 }, { x: 7, z: 6 }, { x: 7, z: 5 }, { x: 7, z: 4 }],
    vanishing: [{ x: 3, z: 7, height: 4 }, { x: 5, z: 7, height: 4 }],
  },
  {
    id: 'map--5-0', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map--5-1' }, { direction: 'east', target: 'map--4-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--4-0', tint: 'cyan', depth: 4,
    exits: [{ direction: 'east', target: 'map--3-0' }, { direction: 'west', target: 'map--5-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 0, height: 3 }, { x: 2, z: 3, height: 3 }, { x: 5, z: 0, height: 3 }, { x: 5, z: 3, height: 3 }],
    balls: [{ from: { x: 2, z: 1 }, to: { x: 5, z: 1 } }, { from: { x: 2, z: 1 }, to: { x: 5, z: 1 } }],
  },
  {
    id: 'map--3-0', tint: 'green', depth: 4,
    exits: [{ direction: 'east', target: 'map--2-0' }, { direction: 'west', target: 'map--4-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 3, height: 1 }],
    floatingBlocks: [{ x: 1, z: 3, bottom: 1 }, { x: 2, z: 3, bottom: 2 }, { x: 3, z: 3, bottom: 3 }, { x: 7, z: 1, bottom: 3 }, { x: 7, z: 2, bottom: 3 }],
    spikes: [{ x: 3, z: 1 }, { x: 3, z: 2 }, { x: 4, z: 1 }, { x: 4, z: 2 }, { x: 5, z: 1 }, { x: 5, z: 2 }, { x: 6, z: 1 }, { x: 6, z: 2 }],
    movingPlatforms: [{ from: { x: 3, z: 0 }, to: { x: 3, z: 1 }, height: 4 }],
  },
  {
    id: 'map--2-0', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map--1-0' }, { direction: 'west', target: 'map--3-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 3, z: 2, bottom: 1 }],
    balls: [{ from: { x: 3, z: 2 }, to: { x: 3, z: 2 } }],
  },
  {
    id: 'map--1-0', tint: 'cyan',
    exits: [{ direction: 'south', target: 'map--1-1' }, { direction: 'east', target: 'room-001' }, { direction: 'north', target: 'map--1--1' }, { direction: 'west', target: 'map--2-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 2, height: 1 }, { x: 2, z: 5, height: 1 }, { x: 5, z: 2, height: 1 }, { x: 5, z: 5, height: 1 }],
    spikes: [{ x: 2, z: 5, height: 1 }, { x: 5, z: 5, height: 1 }, { x: 2, z: 2, height: 1 }, { x: 5, z: 2, height: 1 }],
    portcullises: [{ from: { x: 3, z: 5 }, to: { x: 4, z: 5 } }, { from: { x: 3, z: 2 }, to: { x: 4, z: 2 } }, { from: { x: 2, z: 3 }, to: { x: 2, z: 4 } }, { from: { x: 5, z: 3 }, to: { x: 5, z: 4 } }],
  },
  {
    id: 'room-001', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-0-1' }, { direction: 'east', target: 'map-1-0' }, { direction: 'north', target: 'map-0--1' }, { direction: 'west', target: 'map--1-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 1, z: 2, height: 1 }, { x: 1, z: 5, height: 1 }, { x: 2, z: 1, height: 1 }, { x: 2, z: 6, height: 1 }, { x: 5, z: 1, height: 1 }, { x: 5, z: 6, height: 1 }, { x: 6, z: 2, height: 1 }, { x: 6, z: 5, height: 1 }],
    cauldron: { x: 4, z: 4, height: 0 },
    wizard: { x: 4, z: 2 },
  },
  {
    id: 'map-1-0', tint: 'cyan', depth: 4,
    exits: [{ direction: 'east', target: 'map-2-0' }, { direction: 'west', target: 'room-001' }],
    spawn: { x: 3, z: 0 },
    platforms: [{ x: 4, z: 0, height: 4 }, { x: 4, z: 1, height: 1 }, { x: 4, z: 2, height: 1 }, { x: 4, z: 3, height: 4 }],
    flames: [{ x: 4, z: 2, height: 1 }],
  },
  {
    id: 'map-2-0', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map-3-0' }, { direction: 'west', target: 'map-1-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 0, height: 1 }, { x: 2, z: 1, height: 1 }, { x: 2, z: 2, height: 1 }, { x: 2, z: 3, height: 1 }, { x: 5, z: 0, height: 1 }, { x: 5, z: 1, height: 1 }, { x: 5, z: 2, height: 1 }, { x: 5, z: 3, height: 1 }],
    spikedBalls: [{ x: 2, z: 3, height: 3 }, { x: 2, z: 2, height: 3 }, { x: 2, z: 1, height: 3 }, { x: 2, z: 0, height: 3 }, { x: 5, z: 3, height: 3 }, { x: 5, z: 2, height: 3 }, { x: 5, z: 1, height: 3 }, { x: 5, z: 0, height: 3 }],
  },
  {
    id: 'map-3-0', tint: 'cyan',
    exits: [{ direction: 'south', target: 'map-3-1' }, { direction: 'east', target: 'map-4-0' }, { direction: 'west', target: 'map-2-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-4-0', tint: 'green', depth: 4,
    exits: [{ direction: 'east', target: 'map-5-0' }, { direction: 'west', target: 'map-3-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 0, height: 2 }, { x: 2, z: 3, height: 2 }, { x: 5, z: 0, height: 2 }, { x: 5, z: 3, height: 2 }],
    spikes: [{ x: 2, z: 3, height: 2 }, { x: 5, z: 3, height: 2 }, { x: 2, z: 0, height: 2 }, { x: 5, z: 0, height: 2 }],
    portcullises: [{ from: { x: 2, z: 0 }, to: { x: 2, z: 3 } }, { from: { x: 5, z: 0 }, to: { x: 5, z: 3 } }],
    pathGuards: [{ path: [{ x: 2, z: 1 }, { x: 5, z: 1 }] }],
    pickups: [{ x: 3, z: 2, item: 'poison' }],
  },
  {
    id: 'map-5-0', tint: 'cyan',
    exits: [{ direction: 'east', target: 'map-6-0' }, { direction: 'west', target: 'map-4-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 4, z: 6, height: 3 }, { x: 4, z: 7, height: 1 }],
    floatingBlocks: [{ x: 3, z: 5, bottom: 3 }, { x: 3, z: 6, bottom: 3 }, { x: 3, z: 7, bottom: 3 }, { x: 4, z: 5, bottom: 1 }, { x: 4, z: 7, bottom: 2 }, { x: 4, z: 7, bottom: 3 }, { x: 5, z: 5, bottom: 3 }, { x: 5, z: 6, bottom: 3 }, { x: 5, z: 7, bottom: 3 }],
    spikes: [{ x: 4, z: 4 }],
    balls: [{ from: { x: 2, z: 4 }, to: { x: 5, z: 4 } }],
    pickups: [{ x: 3, z: 3, item: 'boot' }],
  },
  {
    id: 'map-6-0', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map-7-0' }, { direction: 'west', target: 'map-5-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    tables: [{ x: 3, z: 2, height: 1 }, { x: 3, z: 2, height: 2 }],
    ghosts: [{ x: 3, z: 3 }],
  },
  {
    id: 'map-7-0', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-7-1' }, { direction: 'west', target: 'map-6-0' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--5-1', tint: 'green', width: 4,
    exits: [{ direction: 'south', target: 'map--5-2' }, { direction: 'north', target: 'map--5-0' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 3, height: 4 }, { x: 1, z: 3, height: 1 }, { x: 2, z: 3, height: 1 }, { x: 3, z: 3, height: 4 }],
    flames: [{ x: 1, z: 3, height: 1 }],
  },
  {
    id: 'map--1-1', tint: 'green', width: 4,
    exits: [{ direction: 'south', target: 'map--1-2' }, { direction: 'north', target: 'map--1-0' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 3, height: 2 }, { x: 1, z: 3, height: 2 }, { x: 2, z: 3, height: 2 }, { x: 3, z: 3, height: 2 }],
    puzzle: true,
  },
  {
    id: 'map-0-1', tint: 'purple', width: 4,
    exits: [{ direction: 'south', target: 'map-0-2' }, { direction: 'north', target: 'room-001' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 1, z: 6, height: 1 }, { x: 2, z: 1, height: 1 }],
    spikes: [{ x: 0, z: 4 }, { x: 1, z: 4 }, { x: 2, z: 4 }, { x: 3, z: 4 }, { x: 0, z: 3 }, { x: 1, z: 3 }, { x: 2, z: 3 }, { x: 3, z: 3 }],
    vanishing: [{ x: 1, z: 5, height: 2 }, { x: 2, z: 2, height: 2 }, { x: 1, z: 4, height: 3 }, { x: 2, z: 4, height: 3 }, { x: 1, z: 3, height: 3 }, { x: 2, z: 3, height: 3 }],
  },
  {
    id: 'map-3-1', tint: 'purple', width: 4,
    exits: [{ direction: 'south', target: 'map-3-2' }, { direction: 'north', target: 'map-3-0' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 3, z: 6, height: 4 }, { x: 3, z: 7, height: 2 }],
    floatingBlocks: [{ x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }],
    spikes: [{ x: 2, z: 3 }, { x: 3, z: 3 }],
    movingPlatforms: [{ from: { x: 3, z: 2 }, to: { x: 3, z: 5 }, height: 4 }, { from: { x: 0, z: 3 }, to: { x: 1, z: 3 }, height: 4 }],
  },
  {
    id: 'map-7-1', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map-7-2' }, { direction: 'north', target: 'map-7-0' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 3, height: 3 }, { x: 1, z: 3, height: 3 }, { x: 2, z: 3, height: 3 }, { x: 3, z: 3, height: 3 }],
    spikes: [{ x: 1, z: 3, height: 3 }, { x: 2, z: 3, height: 3 }, { x: 3, z: 3, height: 3 }],
    puzzle: true,
  },
  {
    id: 'map--5-2', tint: 'purple', width: 4,
    exits: [{ direction: 'south', target: 'map--5-3' }, { direction: 'north', target: 'map--5-1' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 2, z: 6, height: 2 }, { x: 3, z: 7, height: 2 }],
    floatingBlocks: [{ x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }, { x: 3, z: 6, bottom: 1 }],
    spikes: [{ x: 0, z: 2 }, { x: 2, z: 2 }, { x: 1, z: 4 }, { x: 3, z: 4 }],
    balls: [{ from: { x: 2, z: 5 }, to: { x: 2, z: 5 } }],
    spikedBalls: [{ x: 0, z: 2, height: 1 }, { x: 2, z: 2, height: 1 }, { x: 1, z: 4, height: 1 }, { x: 3, z: 4, height: 1 }],
  },
  {
    id: 'map--1-2', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--1-3' }, { direction: 'north', target: 'map--1-1' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-0-2', tint: 'yellow',
    exits: [{ direction: 'north', target: 'map-0-1' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 5, height: 2 }, { x: 2, z: 6, height: 4 }, { x: 6, z: 2, height: 4 }, { x: 6, z: 6, height: 4 }],
    spikes: [{ x: 5, z: 6 }, { x: 6, z: 3 }],
  },
  {
    id: 'map-2-2', tint: 'purple',
    exits: [{ direction: 'south', target: 'map-2-3' }, { direction: 'east', target: 'map-3-2' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 0, height: 1 }, { x: 0, z: 3, height: 4 }, { x: 0, z: 5, height: 2 }, { x: 1, z: 4, height: 2 }],
    floatingBlocks: [{ x: 0, z: 1, bottom: 1 }, { x: 0, z: 2, bottom: 2 }],
    spikes: [{ x: 0, z: 5, height: 2 }, { x: 1, z: 4, height: 2 }],
    vanishing: [{ x: 0, z: 4, height: 4 }],
    pickups: [{ x: 3, z: 3, item: 'wine-bottle' }],
  },
  {
    id: 'map-3-2', tint: 'green',
    exits: [{ direction: 'south', target: 'map-3-3' }, { direction: 'north', target: 'map-3-1' }, { direction: 'west', target: 'map-2-2' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-7-2', tint: 'green', width: 4,
    exits: [{ direction: 'south', target: 'map-7-3' }, { direction: 'north', target: 'map-7-1' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 1, z: 3, height: 1 }, { x: 1, z: 6, height: 1 }, { x: 2, z: 3, height: 1 }, { x: 2, z: 6, height: 2 }],
  },
  {
    id: 'map--5-3', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map--5-4' }, { direction: 'east', target: 'map--4-3' }, { direction: 'north', target: 'map--5-2' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--4-3', tint: 'green',
    exits: [{ direction: 'west', target: 'map--5-3' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 2, height: 1 }, { x: 3, z: 3, height: 1 }, { x: 3, z: 4, height: 4 }, { x: 4, z: 2, height: 1 }, { x: 5, z: 2, height: 2 }],
    tables: [{ x: 6, z: 5, height: 1 }, { x: 6, z: 5, height: 2 }],
  },
  {
    id: 'map--1-3', tint: 'green', width: 4,
    exits: [{ direction: 'south', target: 'map--1-4' }, { direction: 'north', target: 'map--1-2' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 1, z: 1, height: 1 }, { x: 1, z: 6, height: 1 }, { x: 2, z: 1, height: 1 }, { x: 2, z: 6, height: 1 }],
    ghosts: [{ x: 1, z: 4 }, { x: 2, z: 3 }],
  },
  {
    id: 'map-2-3', tint: 'cyan',
    exits: [{ direction: 'east', target: 'map-3-3' }, { direction: 'north', target: 'map-2-2' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 3, height: 3 }, { x: 3, z: 5, height: 3 }],
    spikes: [{ x: 2, z: 5 }, { x: 2, z: 4 }, { x: 2, z: 4, height: 1 }, { x: 2, z: 4, height: 2 }, { x: 2, z: 3 }, { x: 4, z: 5 }, { x: 4, z: 4 }, { x: 4, z: 4, height: 1 }, { x: 4, z: 4, height: 2 }, { x: 4, z: 3 }],
  },
  {
    id: 'map-3-3', tint: 'yellow',
    exits: [{ direction: 'north', target: 'map-3-2' }, { direction: 'west', target: 'map-2-3' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 4, z: 4, bottom: 1 }, { x: 4, z: 4, bottom: 2 }],
    ghosts: [{ x: 4, z: 4 }],
  },
  {
    id: 'map-7-3', tint: 'purple',
    exits: [{ direction: 'south', target: 'map-7-4' }, { direction: 'north', target: 'map-7-2' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 5, z: 7, height: 1 }],
    floatingBlocks: [{ x: 3, z: 0, bottom: 3 }, { x: 4, z: 0, bottom: 3 }, { x: 6, z: 7, bottom: 1 }, { x: 6, z: 7, bottom: 2 }, { x: 7, z: 7, bottom: 2 }],
    spikes: [{ x: 7, z: 7 }, { x: 7, z: 6 }, { x: 7, z: 5 }, { x: 6, z: 5 }, { x: 5, z: 5 }, { x: 5, z: 4 }, { x: 5, z: 3 }, { x: 5, z: 2 }, { x: 4, z: 2 }, { x: 4, z: 1 }],
    balls: [{ from: { x: 7, z: 7 }, to: { x: 7, z: 7 } }],
  },
  {
    id: 'map--5-4', tint: 'purple', width: 4,
    exits: [{ direction: 'south', target: 'map--5-5' }, { direction: 'north', target: 'map--5-3' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 3, height: 3 }, { x: 1, z: 3, height: 3 }, { x: 2, z: 3, height: 3 }, { x: 3, z: 3, height: 3 }],
    puzzle: true,
  },
  {
    id: 'map--1-4', tint: 'cyan',
    exits: [{ direction: 'south', target: 'map--1-5' }, { direction: 'north', target: 'map--1-3' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 3, z: 3, bottom: 1 }],
    ghosts: [{ x: 3, z: 3 }],
  },
  {
    id: 'map-7-4', tint: 'green', width: 4,
    exits: [{ direction: 'south', target: 'map-7-5' }, { direction: 'north', target: 'map-7-3' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    ghosts: [{ x: 2, z: 3 }],
  },
  {
    id: 'map--8-5', tint: 'cyan',
    exits: [{ direction: 'south', target: 'map--8-6' }, { direction: 'east', target: 'map--7-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 0, height: 1 }, { x: 4, z: 3, height: 4 }],
    floatingBlocks: [{ x: 0, z: 0, bottom: 3 }, { x: 0, z: 1, bottom: 3 }, { x: 0, z: 2, bottom: 3 }, { x: 0, z: 3, bottom: 3 }, { x: 0, z: 4, bottom: 3 }, { x: 1, z: 0, bottom: 2 }, { x: 2, z: 0, bottom: 1 }],
    spikes: [{ x: 3, z: 3 }, { x: 4, z: 4 }, { x: 5, z: 3 }, { x: 4, z: 2 }],
  },
  {
    id: 'map--7-5', tint: 'green', depth: 4,
    exits: [{ direction: 'east', target: 'map--6-5' }, { direction: 'west', target: 'map--8-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    spikes: [{ x: 6, z: 1 }, { x: 6, z: 2 }, { x: 3, z: 1 }, { x: 4, z: 1 }, { x: 3, z: 2 }, { x: 4, z: 2 }, { x: 1, z: 1 }, { x: 1, z: 2 }],
    pathGuards: [{ path: [{ x: 0, z: 0 }, { x: 7, z: 0 }] }],
  },
  {
    id: 'map--6-5', tint: 'cyan',
    exits: [{ direction: 'south', target: 'map--6-6' }, { direction: 'west', target: 'map--7-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 0, height: 1 }, { x: 7, z: 4, height: 1 }],
    floatingBlocks: [{ x: 4, z: 0, bottom: 1 }, { x: 5, z: 0, bottom: 2 }, { x: 6, z: 0, bottom: 3 }, { x: 6, z: 1, bottom: 3 }, { x: 7, z: 0, bottom: 3 }, { x: 7, z: 1, bottom: 3 }, { x: 7, z: 2, bottom: 2 }, { x: 7, z: 3, bottom: 1 }],
    spikedBalls: [{ x: 7, z: 1, height: 0, bobs: true }, { x: 6, z: 0, height: 0, bobs: true }],
  },
  {
    id: 'map--5-5', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map--5-6' }, { direction: 'north', target: 'map--5-4' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 5, height: 1 }, { x: 3, z: 5, height: 1 }],
    spikes: [{ x: 0, z: 5, height: 1 }, { x: 3, z: 5, height: 1 }, { x: 0, z: 3 }, { x: 3, z: 3 }],
    portcullises: [{ from: { x: 0, z: 5 }, to: { x: 3, z: 5 } }],
    pathGuards: [{ path: [{ x: 0, z: 4 }, { x: 3, z: 4 }] }],
  },
  {
    id: 'map--2-5', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map--2-6' }, { direction: 'east', target: 'map--1-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 4, z: 2, height: 3 }, { x: 4, z: 3, height: 1 }, { x: 4, z: 4, height: 1 }, { x: 4, z: 5, height: 4 }],
    balls: [{ from: { x: 5, z: 3 }, to: { x: 5, z: 3 } }, { from: { x: 0, z: 3 }, to: { x: 3, z: 3 } }],
  },
  {
    id: 'map--1-5', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--1-6' }, { direction: 'east', target: 'map-0-5' }, { direction: 'north', target: 'map--1-4' }, { direction: 'west', target: 'map--2-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    flames: [{ x: 3, z: 3, height: 0 }, { x: 4, z: 4, height: 0 }, { x: 3, z: 4, height: 0 }, { x: 4, z: 3, height: 0 }],
  },
  {
    id: 'map-0-5', tint: 'purple',
    exits: [{ direction: 'south', target: 'map-0-6' }, { direction: 'east', target: 'map-1-5' }, { direction: 'west', target: 'map--1-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-1-5', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-1-6' }, { direction: 'west', target: 'map-0-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-5-5', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-5-6' }, { direction: 'east', target: 'map-6-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 6, z: 3, height: 1 }, { x: 6, z: 4, height: 1 }, { x: 7, z: 2, height: 1 }, { x: 7, z: 5, height: 1 }],
    floatingBlocks: [{ x: 7, z: 3, bottom: 3 }, { x: 7, z: 4, bottom: 3 }],
    tables: [{ x: 2, z: 3, height: 1 }, { x: 2, z: 3, height: 2 }, { x: 2, z: 3, height: 3 }, { x: 2, z: 3, height: 4 }],
  },
  {
    id: 'map-6-5', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map-7-5' }, { direction: 'west', target: 'map-5-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-7-5', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-7-6' }, { direction: 'north', target: 'map-7-4' }, { direction: 'west', target: 'map-6-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 3, height: 4 }],
    floatingBlocks: [{ x: 2, z: 4, bottom: 3 }],
    spikes: [{ x: 3, z: 2 }, { x: 4, z: 3 }, { x: 3, z: 4 }, { x: 2, z: 3 }],
    vanishing: [{ x: 2, z: 2, height: 1 }, { x: 4, z: 2, height: 2 }, { x: 4, z: 4, height: 3 }],
  },
  {
    id: 'map--8-6', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map--8-7' }, { direction: 'north', target: 'map--8-5' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    spikes: [{ x: 0, z: 7 }, { x: 3, z: 7 }, { x: 1, z: 5 }, { x: 2, z: 5 }, { x: 1, z: 2 }, { x: 2, z: 2 }, { x: 0, z: 0 }, { x: 3, z: 0 }],
  },
  {
    id: 'map--6-6', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map--6-7' }, { direction: 'north', target: 'map--6-5' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    spikedBalls: [{ x: 3, z: 0, height: 0 }, { x: 0, z: 1, height: 0 }, { x: 2, z: 1, height: 0 }, { x: 1, z: 2, height: 0 }, { x: 3, z: 2, height: 0 }, { x: 0, z: 3, height: 0 }, { x: 2, z: 3, height: 0 }, { x: 1, z: 4, height: 0 }, { x: 3, z: 4, height: 0 }, { x: 0, z: 5, height: 0 }, { x: 2, z: 5, height: 0 }, { x: 1, z: 6, height: 0 }, { x: 3, z: 6, height: 0 }, { x: 0, z: 7, height: 0 }],
    puzzle: true,
  },
  {
    id: 'map--5-6', tint: 'yellow', width: 4,
    exits: [{ direction: 'south', target: 'map--5-7' }, { direction: 'north', target: 'map--5-5' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
    vanishing: [{ x: 0, z: 0, height: 1 }, { x: 3, z: 0, height: 1 }, { x: 0, z: 1, height: 2 }, { x: 3, z: 1, height: 2 }, { x: 0, z: 2, height: 3 }, { x: 3, z: 2, height: 3 }, { x: 0, z: 5, height: 3 }, { x: 3, z: 5, height: 3 }, { x: 0, z: 6, height: 2 }, { x: 3, z: 6, height: 2 }, { x: 0, z: 7, height: 1 }, { x: 3, z: 7, height: 1 }, { x: 0, z: 3, height: 4 }, { x: 3, z: 3, height: 4 }, { x: 0, z: 4, height: 4 }, { x: 3, z: 4, height: 4 }],
    balls: [{ from: { x: 0, z: 3 }, to: { x: 3, z: 3 } }],
  },
  {
    id: 'map--2-6', tint: 'purple',
    exits: [{ direction: 'south', target: 'map--2-7' }, { direction: 'east', target: 'map--1-6' }, { direction: 'north', target: 'map--2-5' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--1-6', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map--1-7' }, { direction: 'east', target: 'map-0-6' }, { direction: 'north', target: 'map--1-5' }, { direction: 'west', target: 'map--2-6' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    spikes: [{ x: 3, z: 6 }, { x: 4, z: 6 }, { x: 1, z: 4 }, { x: 1, z: 3 }, { x: 6, z: 4 }, { x: 6, z: 3 }, { x: 3, z: 1 }, { x: 4, z: 1 }],
  },
  {
    id: 'map-0-6', tint: 'yellow',
    exits: [{ direction: 'south', target: 'map-0-7' }, { direction: 'east', target: 'map-1-6' }, { direction: 'north', target: 'map-0-5' }, { direction: 'west', target: 'map--1-6' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 1, z: 4, height: 1 }, { x: 3, z: 2, height: 1 }, { x: 3, z: 4, height: 4 }, { x: 3, z: 6, height: 1 }, { x: 5, z: 4, height: 1 }],
    spikes: [{ x: 3, z: 5 }, { x: 4, z: 4 }, { x: 3, z: 3 }, { x: 2, z: 4 }],
  },
  {
    id: 'map-1-6', tint: 'purple',
    exits: [{ direction: 'south', target: 'map-1-7' }, { direction: 'north', target: 'map-1-5' }, { direction: 'west', target: 'map-0-6' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-5-6', tint: 'green', width: 4,
    exits: [{ direction: 'south', target: 'map-5-7' }, { direction: 'north', target: 'map-5-5' }],
    spawn: { x: 2, z: 0 },
    platforms: [{ x: 0, z: 3, height: 3 }, { x: 1, z: 3, height: 3 }, { x: 2, z: 3, height: 3 }, { x: 3, z: 3, height: 3 }],
    puzzle: true,
  },
  {
    id: 'map-7-6', tint: 'cyan', width: 4,
    exits: [{ direction: 'south', target: 'map-7-7' }, { direction: 'north', target: 'map-7-5' }],
    spawn: { x: 2, z: 0 },
    platforms: [],
  },
  {
    id: 'map--8-7', tint: 'cyan',
    exits: [{ direction: 'east', target: 'map--7-7' }, { direction: 'north', target: 'map--8-6' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    floatingBlocks: [{ x: 0, z: 0, bottom: 3 }, { x: 0, z: 2, bottom: 3 }, { x: 0, z: 5, bottom: 2 }, { x: 0, z: 7, bottom: 1 }, { x: 1, z: 0, bottom: 3 }, { x: 2, z: 0, bottom: 3 }, { x: 3, z: 0, bottom: 3 }, { x: 4, z: 0, bottom: 3 }, { x: 6, z: 7, bottom: 3 }, { x: 7, z: 3, bottom: 3 }, { x: 7, z: 4, bottom: 3 }, { x: 7, z: 7, bottom: 3 }],
    spikes: [{ x: 1, z: 7 }, { x: 3, z: 7 }],
    movingPlatforms: [{ from: { x: 2, z: 7 }, to: { x: 7, z: 7 }, height: 4 }],
  },
  {
    id: 'map--7-7', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map--6-7' }, { direction: 'west', target: 'map--8-7' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    balls: [{ from: { x: 3, z: 2 }, to: { x: 3, z: 2 } }],
  },
  {
    id: 'map--6-7', tint: 'cyan',
    exits: [{ direction: 'east', target: 'map--5-7' }, { direction: 'north', target: 'map--6-6' }, { direction: 'west', target: 'map--7-7' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map--5-7', tint: 'purple',
    exits: [{ direction: 'north', target: 'map--5-6' }, { direction: 'west', target: 'map--6-7' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 6, height: 2 }, { x: 2, z: 7, height: 2 }, { x: 3, z: 5, height: 2 }, { x: 4, z: 6, height: 2 }, { x: 4, z: 7, height: 2 }],
    floatingBlocks: [{ x: 3, z: 6, bottom: 2 }, { x: 3, z: 7, bottom: 2 }],
    ghosts: [{ x: 3, z: 6 }],
  },
  {
    id: 'map--2-7', tint: 'yellow',
    exits: [{ direction: 'east', target: 'map--1-7' }, { direction: 'north', target: 'map--2-6' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 3, z: 3, height: 4 }],
    pushBlocks: [{ x: 2, z: 2 }],
    tables: [{ x: 4, z: 6, height: 1 }],
    vanishing: [{ x: 4, z: 3, height: 1 }],
  },
  {
    id: 'map--1-7', tint: 'purple',
    exits: [{ direction: 'east', target: 'map-0-7' }, { direction: 'north', target: 'map--1-6' }, { direction: 'west', target: 'map--2-7' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 2, z: 2, height: 1 }, { x: 2, z: 3, height: 1 }, { x: 2, z: 4, height: 1 }, { x: 3, z: 2, height: 1 }, { x: 3, z: 4, height: 1 }, { x: 4, z: 2, height: 1 }, { x: 4, z: 3, height: 1 }, { x: 4, z: 4, height: 1 }],
    floatingBlocks: [{ x: 3, z: 3, bottom: 1 }],
    balls: [{ from: { x: 3, z: 3 }, to: { x: 3, z: 3 } }],
  },
  {
    id: 'map-0-7', tint: 'purple',
    exits: [{ direction: 'east', target: 'map-1-7' }, { direction: 'north', target: 'map-0-6' }, { direction: 'west', target: 'map--1-7' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
  },
  {
    id: 'map-1-7', tint: 'yellow',
    exits: [{ direction: 'north', target: 'map-1-6' }, { direction: 'west', target: 'map-0-7' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    spikedBalls: [{ x: 7, z: 7, height: 3, bobs: true }, { x: 6, z: 7, height: 3, bobs: true }, { x: 6, z: 6, height: 3, bobs: true }, { x: 7, z: 6, height: 3, bobs: true }, { x: 5, z: 7, height: 3, bobs: true }, { x: 7, z: 5, height: 3, bobs: true }, { x: 3, z: 0, height: 3, bobs: true }, { x: 4, z: 0, height: 3, bobs: true }, { x: 0, z: 3, height: 3, bobs: true }, { x: 0, z: 4, height: 3, bobs: true }],
  },
  {
    id: 'map-5-7', tint: 'yellow',
    exits: [{ direction: 'east', target: 'map-6-7' }, { direction: 'north', target: 'map-5-6' }],
    spawn: { x: 4, z: 0 },
    platforms: [{ x: 0, z: 5, height: 1 }, { x: 1, z: 5, height: 1 }, { x: 2, z: 5, height: 1 }, { x: 2, z: 6, height: 1 }, { x: 2, z: 7, height: 1 }],
    floatingBlocks: [{ x: 0, z: 6, bottom: 1 }, { x: 0, z: 7, bottom: 2 }, { x: 1, z: 6, bottom: 1 }, { x: 1, z: 7, bottom: 1 }],
  },
  {
    id: 'map-6-7', tint: 'purple', depth: 4,
    exits: [{ direction: 'east', target: 'map-7-7' }, { direction: 'west', target: 'map-5-7' }],
    spawn: { x: 5, z: 0 },
    platforms: [{ x: 3, z: 0, height: 1 }, { x: 3, z: 3, height: 1 }, { x: 4, z: 0, height: 1 }, { x: 4, z: 3, height: 1 }],
    spikes: [{ x: 5, z: 2 }, { x: 5, z: 1 }, { x: 2, z: 2 }, { x: 2, z: 1 }],
    balls: [{ from: { x: 3, z: 1 }, to: { x: 4, z: 1 } }],
  },
  {
    id: 'map-7-7', tint: 'yellow',
    exits: [{ direction: 'north', target: 'map-7-6' }, { direction: 'west', target: 'map-6-7' }],
    spawn: { x: 4, z: 0 },
    platforms: [],
    spikes: [{ x: 6, z: 5 }, { x: 5, z: 6 }, { x: 7, z: 6 }, { x: 6, z: 7 }],
  },
]
