"""Extract the original's beeper tunes into src/engine/tunes.ts.

The player at 0xB2C5 walks a tune one byte at a time until 0xFF: the low 6
bits pick a note from the table at 0xB332 (0 is a rest), the top 2 bits give
its length, 1 to 4 units. A table entry is (B, C, cycles): each half of the
square wave waits a DJNZ loop of B then C-1 passes of 256, and the note plays
cycles x length full waves. A rest waits 17163 x 26 T-states per unit. The
Spectrum's Z80 runs at 3.5 MHz.

usage (from the repo root): python3 tools/rip/music.py"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from z80 import load_memory  # noqa: E402

SNAPSHOT = 'reference/KnightLore.z80'
OUT = 'src/engine/tunes.ts'
CLOCK_HZ = 3_500_000
NOTE_TABLE = 0xB332
REST_T_STATES = 17163 * 26
# Where the game hands the player a tune, and what it plays it for: the
# new-game setup at 0xAF7D (it also sets five lives), the results screen at
# 0xBA29 that ends every game, and the cure message at 0xBAAB that comes
# before it when the potion is brewed.
TUNES = {'game_start': 0xB20E, 'game_over': 0xB218, 'cure': 0xB239}


def half_period_t_states(b, c):
    first_run = ((b or 256) - 1) * 13 + 8
    later_runs = (c - 1) * (4 + 12 + 255 * 13 + 8)
    return first_run + later_runs + 4 + 7 + 10 + 11 + 7 + 11


def decode(memory, address):
    notes = []
    while memory[address] != 0xFF:
        value = memory[address]
        index, length = value & 0x3F, (value >> 6) + 1
        if index == 0:
            notes.append((0, round(length * REST_T_STATES / CLOCK_HZ, 4)))
        else:
            b, c, cycles = memory[NOTE_TABLE + 3 * index:NOTE_TABLE + 3 * index + 3]
            frequency = CLOCK_HZ / (2 * half_period_t_states(b, c))
            notes.append((round(frequency, 1), round(cycles * length / frequency, 4)))
        address += 1
    return notes


def typescript(tunes):
    lines = ['// Generated by tools/rip/music.py from the original\'s memory. Do not edit.',
             "import type { Note } from './Beeper'", '']
    for name, notes in tunes.items():
        body = ', '.join(f'{{ frequency: {f}, duration: {d} }}' for f, d in notes)
        lines.append(f'export const {name.upper()}_TUNE: Note[] = [{body}]')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    memory = load_memory(SNAPSHOT)
    with open(OUT, 'w') as out:
        out.write(typescript({name: decode(memory, address) for name, address in TUNES.items()}))
